export type Language = 'en' | 'hi' | 'ta' | 'te' | 'kn' | 'ml';

export const reportTranslations = {
  en: {
    // ── Identity ────────────────────────────────────────────────────────────
    title: 'LoanGuard Compliance Report',
    subtitle: 'Loan Agreement Analysis',
    generatedOn: 'Generated on',
    bank: 'Bank/NBFC',
    borrower: 'Borrower Name',
    agreementDate: 'Agreement Date',
    selectLanguage: 'Report Language',
    downloadButton: 'Download PDF Report',
    noData: 'No analysis data available. Upload and analyze a loan document first.',

    // ── Confidence & Document Quality ───────────────────────────────────────
    systemConfidence: 'System Confidence',
    docCompleteness: 'Document Completeness',     // NEW
    lowConfidenceWarning: 'Low Confidence Warning', // NEW

    // ── Compliance Assessment ───────────────────────────────────────────────
    complianceAssessment: 'Compliance Assessment Summary',
    violationsFound: 'Violations Found',
    critical: 'Critical',
    high: 'High',
    overchargeEstimate: 'Est. Overcharge',
    riskCategory: 'Risk Category',
    appealSuccessProbability: 'Appeal Success Probability',
    mathProven: 'Math-Proven Violations',         // NEW
    kfsPresent: 'Key Facts Statement',            // NEW

    // ── Loan Details ────────────────────────────────────────────────────────
    loanDetails: 'Loan Details',
    principal: 'Principal',
    interestRate: 'Interest Rate',
    effectiveAPR: 'Effective APR',
    tenure: 'Tenure',
    expectedEMI: 'Expected EMI',
    statedEMI: 'Stated EMI',
    processingFee: 'Processing Fee',
    overchargeEst: 'Overcharge Est.',
    months: 'months',
    prepaymentPenalty: 'Prepayment Penalty',      // NEW
    insurancePremium: 'Insurance Premium',        // NEW

    // ── Flags ───────────────────────────────────────────────────────────────
    flags: 'Identified Flags',
    autoDebit: 'Auto-Debit Mandate',

    // ── Risk Intelligence ───────────────────────────────────────────────────
    riskIntelligence: 'Risk Intelligence Score',
    score: 'Score',
    lowRisk: 'LOW RISK',
    emiDeviation: 'EMI Deviation',
    hiddenFees: 'Hidden Fees',
    rbiViolations: 'RBI Violations',
    penalStacking: 'Penal Stacking',
    transparency: 'Transparency',
    ambiguity: 'Ambiguity',
    behavioralRisk: 'Behavioral Risk',            // NEW

    // ── EMI Analysis ────────────────────────────────────────────────────────
    emiAnalysis: 'EMI Analysis',
    emiNote: 'Deterministic EMI calculation shows {deviation}% deviation from stated values.',

    // ── Disclaimer ──────────────────────────────────────────────────────────
    disclaimer:
      'This report is generated by LoanGuard AI and is for informational purposes only. It is not a substitute for licensed legal counsel, regulatory guidance, or professional financial advice. Users are advised to consult qualified lawyers and financial advisors before taking any action based on this report. LoanGuard does not guarantee the accuracy or completeness of information extracted from loan documents.',
  },

  hi: {
    title: 'LoanGuard अनुपालन रिपोर्ट',
    subtitle: 'ऋण समझौता विश्लेषण',
    generatedOn: 'के रूप में तैयार',
    bank: 'बैंक/NBFC',
    borrower: 'उधारकर्ता का नाम',
    agreementDate: 'समझौता तिथि',
    selectLanguage: 'रिपोर्ट भाषा',
    downloadButton: 'PDF रिपोर्ट डाउनलोड करें',
    noData: 'कोई विश्लेषण डेटा उपलब्ध नहीं है। पहले एक ऋण दस्तावेज़ अपलोड और विश्लेषण करें।',

    systemConfidence: 'सिस्टम आत्मविश्वास',
    docCompleteness: 'दस्तावेज़ पूर्णता',           // NEW
    lowConfidenceWarning: 'कम विश्वास चेतावनी',     // NEW

    complianceAssessment: 'अनुपालन मूल्यांकन सारांश',
    violationsFound: 'पाए गए उल्लंघन',
    critical: 'गंभीर',
    high: 'उच्च',
    overchargeEstimate: 'अनुमानित अतिरिक्त शुल्क',
    riskCategory: 'जोखिम श्रेणी',
    appealSuccessProbability: 'अपील की सफलता की संभावना',
    mathProven: 'गणितीय रूप से सिद्ध उल्लंघन',    // NEW
    kfsPresent: 'मुख्य तथ्य विवरण',                // NEW

    loanDetails: 'ऋण विवरण',
    principal: 'मूलधन',
    interestRate: 'ब्याज दर',
    effectiveAPR: 'प्रभावी APR',
    tenure: 'अवधि',
    expectedEMI: 'अपेक्षित EMI',
    statedEMI: 'दर्ज EMI',
    processingFee: 'प्रसंस्करण शुल्क',
    overchargeEst: 'अनुमानित अतिरिक्त शुल्क',
    months: 'महीने',
    prepaymentPenalty: 'पूर्व भुगतान शुल्क',       // NEW
    insurancePremium: 'बीमा प्रीमियम',              // NEW

    flags: 'चिन्हित किए गए झंडे',
    autoDebit: 'ऑटो-डेबिट जनादेश',

    riskIntelligence: 'जोखिम बुद्धिमत्ता स्कोर',
    score: 'स्कोर',
    lowRisk: 'कम जोखिम',
    emiDeviation: 'EMI विचलन',
    hiddenFees: 'छिपे हुए शुल्क',
    rbiViolations: 'RBI उल्लंघन',
    penalStacking: 'दंडात्मक स्टैकिंग',
    transparency: 'पारदर्शिता',
    ambiguity: 'अस्पष्टता',
    behavioralRisk: 'व्यवहारिक जोखिम',             // NEW

    emiAnalysis: 'EMI विश्लेषण',
    emiNote: 'नियतार्थी EMI गणना दर्ज मूल्यों से {deviation}% विचलन दर्शाती है।',

    disclaimer:
      'यह रिपोर्ट LoanGuard AI द्वारा तैयार की गई है और केवल सूचनात्मक उद्देश्यों के लिए है। यह लाइसेंस प्राप्त कानूनी सलाह, नियामक मार्गदर्शन, या व्यावसायिक वित्तीय सलाह का विकल्प नहीं है। उपयोगकर्ताओं को सलाह दी जाती है कि इस रिपोर्ट के आधार पर कोई भी कार्रवाई करने से पहले योग्य वकीलों और वित्तीय सलाहकारों से परामर्श लें।',
  },

  ta: {
    title: 'LoanGuard இணக்கம் அறிக்கை',
    subtitle: 'கடன் ஒப்பந்தம் பகுப்பாய்வு',
    generatedOn: 'உருவாக்கப்பட்ட',
    bank: 'வங்கி/NBFC',
    borrower: 'கடனளிக்கப்பட்டவரின் பெயர்',
    agreementDate: 'ஒப்பந்த தேதி',
    selectLanguage: 'அறிக்கை மொழி',
    downloadButton: 'PDF அறிக்கை பதிவிறக்கவும்',
    noData: 'தகவல் பகுப்பாய்வு உபலப்தி இல்லை. முதலில் ஒரு கடன் ஆவணத்தை பதிவேற்றவும்.',

    systemConfidence: 'கணினி நம்பிக்கை',
    docCompleteness: 'ஆவண முழுமை',                       // NEW
    lowConfidenceWarning: 'குறைந்த நம்பிக்கை எச்சரிக்கை', // NEW

    complianceAssessment: 'இணக்கம் மதிப்பீடு சுருக்கம்',
    violationsFound: 'கண்டுபிடிக்கப்பட்ட மீறல்கள்',
    critical: 'முக்கிய',
    high: 'உச்சம்',
    overchargeEstimate: 'மதிப்பிடப்பட்ட அதிக கட்டணம்',
    riskCategory: 'ஆபத்து வகை',
    appealSuccessProbability: 'மேல்முறையீட்டு வெற்றி நிகழ்தகவு',
    mathProven: 'கணிதரீதியாக நிரூபிக்கப்பட்ட மீறல்கள்',  // NEW
    kfsPresent: 'முக்கிய தகவல் அறிக்கை',                  // NEW

    loanDetails: 'கடன் விவரங்கள்',
    principal: 'முதல் தொகை',
    interestRate: 'வட்டி விகிதம்',
    effectiveAPR: 'பயனுள்ள APR',
    tenure: 'கால அவதி',
    expectedEMI: 'எதிர்பார்க்கப்பட்ட EMI',
    statedEMI: 'கூறப்பட்ட EMI',
    processingFee: 'செயல்பாட்டு கட்டணம்',
    overchargeEst: 'அதிக கட்டணம் அனுமானம்',
    months: 'மாதங்கள்',
    prepaymentPenalty: 'முன் கட்டண அபராதம்',              // NEW
    insurancePremium: 'காப்பீட்டு பிரீமியம்',             // NEW

    flags: 'அடையாளம் காணப்பட்ட நிலைகள்',
    autoDebit: 'தானியங்கி-டெபிட் நிறுத்தம்',

    riskIntelligence: 'ஆபத்து நுகர்வு மதிப்பெண்',
    score: 'மதிப்பெண்',
    lowRisk: 'குறைந்த ஆபத்து',
    emiDeviation: 'EMI விலகல்',
    hiddenFees: 'மறைக்கப்பட்ட கட்டணங்கள்',
    rbiViolations: 'RBI மீறல்கள்',
    penalStacking: 'தண்ட அடுக்கு',
    transparency: 'வெளிப்படைத்தன்மை',
    ambiguity: 'தெளிவின்மை',
    behavioralRisk: 'நடத்தை ஆபத்து',                      // NEW

    emiAnalysis: 'EMI பகுப்பாய்வு',
    emiNote: 'தீர்மான EMI கணக்கீடு கூறப்பட்ட மதிப்புகளிலிருந்து {deviation}% விலகல் காட்டுகிறது.',

    disclaimer:
      'இந்த அறிக்கை LoanGuard AI இல் உருவாக்கப்பட்டுள்ளது மற்றும் தகவல் நோக்கங்களுக்கு மட்டுமே உள்ளது. இது உரிமம் பெற்ற சட்ட ஆலோசனை, ஒழுங்குமுறை வழிகாட்டுதல் அல்லது தொழில்முறை நிதி ஆலோசனைக்கு பதிலாக இல்லை.',
  },

  te: {
    title: 'LoanGuard సమ్మతి నివేదన',
    subtitle: 'రుణ ఒప్పందం విశ్లేషణ',
    generatedOn: 'ఉత్పత్తి చేయబడింది',
    bank: 'బ్యాంకు/NBFC',
    borrower: 'రుణగ్రహీత పేరు',
    agreementDate: 'ఒప్పందం తేదీ',
    selectLanguage: 'నివేదన భాష',
    downloadButton: 'PDF నివేదన డౌన్‌లోడ్ చేయండి',
    noData: 'విశ్లేషణ డేటా అందుబాటులో లేదు. మొదట రుణ పత్రాన్ని అప్‌లోడ్ చేసి విశ్లేషించండి.',

    systemConfidence: 'సిస్టమ్ విశ్వాసం',
    docCompleteness: 'పత్రం సంపూర్ణత',                    // NEW
    lowConfidenceWarning: 'తక్కువ విశ్వాస హెచ్చరిక',      // NEW

    complianceAssessment: 'సమ్మతి మూల్యాంకన సారాంశం',
    violationsFound: 'లంఘనలు కనుగొనబడ్డాయి',
    critical: 'సంక్షుబ్ధం',
    high: 'ఎత్తైన',
    overchargeEstimate: 'అంచనా చేసిన అధిక ఛార్జ్',
    riskCategory: 'ప్రమాద వర్గం',
    appealSuccessProbability: 'విజ్ఞప్తి సాఫల్య సంభావ్యత',
    mathProven: 'గణితపరంగా నిరూపించబడిన లంఘనలు',          // NEW
    kfsPresent: 'కీలక వాస్తవాల ప్రకటన',                   // NEW

    loanDetails: 'రుణ వివరాలు',
    principal: 'అసలు',
    interestRate: 'వడ్డీ రేటు',
    effectiveAPR: 'ప్రభావవంతమైన APR',
    tenure: 'కాలవ్యవధి',
    expectedEMI: 'నిర్ణీత EMI',
    statedEMI: 'పేర్కొన్న EMI',
    processingFee: 'ప్రక్రియ రుసుము',
    overchargeEst: 'అధిక ఛార్జ్ అంచనా',
    months: 'నెలలు',
    prepaymentPenalty: 'ముందస్తు చెల్లింపు జరిమానా',       // NEW
    insurancePremium: 'బీమా ప్రీమియం',                     // NEW

    flags: 'గుర్తించిన జెండాలు',
    autoDebit: 'స్వయం-డెబిట్ ఆదేశం',

    riskIntelligence: 'ప్రమాద గుణధర్మం స్కోర్',
    score: 'స్కోర్',
    lowRisk: 'తక్కువ ప్రమాదం',
    emiDeviation: 'EMI విచలనం',
    hiddenFees: 'దాచిన రుసుములు',
    rbiViolations: 'RBI లంఘనలు',
    penalStacking: 'శిక్ష స్టాకింగ్',
    transparency: 'పారదర్శకత',
    ambiguity: 'అస్పష్టత',
    behavioralRisk: 'ప్రవర్తనా ప్రమాదం',                   // NEW

    emiAnalysis: 'EMI విశ్లేషణ',
    emiNote: 'నిర్ణీత EMI గణన పేర్కొన్న విలువల నుండి {deviation}% విచలనాన్ని చూపుతుంది.',

    disclaimer:
      'ఈ నివేదన LoanGuard AI చేత రూపొందించబడింది మరియు సమాచార ప్రయోజనాలకు మాత్రమే ఉంటుంది. ఇది లైసెన్సుకు గల చట్ట సలహా, నియంత్రక మార్గదర్శకం లేదా వృత్తిపరమైన ఆర్థిక సలహాకు ప్రత్యామ్నాయం కాదు.',
  },

  kn: {
    title: 'LoanGuard ಅನುವರ್ತನೆ ವರದಿ',
    subtitle: 'ಸಾಲ ಒಪ್ಪಂದ ವಿಶ್ಲೇಷಣೆ',
    generatedOn: 'ರಚಿಸಿದ',
    bank: 'ಬ್ಯಾಂಕ್/NBFC',
    borrower: 'ಸಾಲಗ್ರಾಹಕ ಹೆಸರು',
    agreementDate: 'ಒಪ್ಪಂದ ದಿನಾಂಕ',
    selectLanguage: 'ವರದಿ ಭಾಷೆ',
    downloadButton: 'PDF ವರದಿ ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ',
    noData: 'ವಿಶ್ಲೇಷಣೆ ಡಾಟಾ ಲಭ್ಯವಿಲ್ಲ. ಮೊದಲು ಸಾಲ ದಾಖಲೆ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ ಮತ್ತು ವಿಶ್ಲೇಷಿಸಿ.',

    systemConfidence: 'ವ್ಯವಸ್ಥೆ ಆತ್ಮವಿಶ್ವಾಸ',
    docCompleteness: 'ದಾಖಲೆ ಸಂಪೂರ್ಣತೆ',                  // NEW
    lowConfidenceWarning: 'ಕಡಿಮೆ ವಿಶ್ವಾಸ ಎಚ್ಚರಿಕೆ',       // NEW

    complianceAssessment: 'ಅನುವರ್ತನೆ ಮೌಲ್ಯಮಾಪನ ಸಾರಾಂಶ',
    violationsFound: 'ಕಂಡುಬಂದ ಉಲ್ಲಂಘನೆಗಳು',
    critical: 'ಸಂಕಟ',
    high: 'ಹೆಚ್ಚಿನ',
    overchargeEstimate: 'ಅಂದಾಜು ಅತಿರಿಕ್ತ ಶುಲ್ಕ',
    riskCategory: 'ಅಪಾಯ ವರ್ಗ',
    appealSuccessProbability: 'ಅರ್ಜಿ ಯಶಸ್ಸಿನ ಸಂಭವನೀಯತೆ',
    mathProven: 'ಗಣಿತೀಯವಾಗಿ ಸಾಬೀತಾದ ಉಲ್ಲಂಘನೆಗಳು',        // NEW
    kfsPresent: 'ಪ್ರಮುಖ ಸತ್ಯ ಹೇಳಿಕೆ',                     // NEW

    loanDetails: 'ಸಾಲ ವಿವರಣೆಗಳು',
    principal: 'ಮೂಲ',
    interestRate: 'ಬಡ್ಡಿ ದರ',
    effectiveAPR: 'ಪ್ರಭಾವಶಾಲೀ APR',
    tenure: 'ಅವಧಿ',
    expectedEMI: 'ನಿರೀಕ್ಷಿತ EMI',
    statedEMI: 'ಹೇಳಿದ EMI',
    processingFee: 'ಪ್ರಕ್ರಿಯೆ ಶುಲ್ಕ',
    overchargeEst: 'ಅತಿರಿಕ್ತ ಶುಲ್ಕ ಅಂದಾಜು',
    months: 'ತಿಂಗಳುಗಳು',
    prepaymentPenalty: 'ಮುಂಗಡ ಪಾವತಿ ದಂಡ',                 // NEW
    insurancePremium: 'ವಿಮಾ ಪ್ರೀಮಿಯಂ',                    // NEW

    flags: 'ಗುರುತಿಸಿದ ಫ್ಲ್ಯಾಗ್‌ಗಳು',
    autoDebit: 'ಸ್ವಯಂ-ಡೆಬಿಟ್ ನಿರ್ದೇಶನ',

    riskIntelligence: 'ಅಪಾಯ ಬುದ್ಧಿಮತ್ತೆ ಸ್ಕೋರ್',
    score: 'ಸ್ಕೋರ್',
    lowRisk: 'ಕಡಿಮೆ ಅಪಾಯ',
    emiDeviation: 'EMI ವಿಚಲನ',
    hiddenFees: 'ಮರೆಮಾಡಿದ ಶುಲ್ಕಗಳು',
    rbiViolations: 'RBI ಉಲ್ಲಂಘನೆಗಳು',
    penalStacking: 'ದಂಡಾತ್ಮಕ ಸ್ಟ್ಯಾಕಿಂಗ್',
    transparency: 'ಪಾರದರ್ಶಕತೆ',
    ambiguity: 'ದ್ವಿರ್ಥತೆ',
    behavioralRisk: 'ವರ್ತನೆಯ ಅಪಾಯ',                       // NEW

    emiAnalysis: 'EMI ವಿಶ್ಲೇಷಣೆ',
    emiNote: 'ನಿರ್ಧಾರಕ EMI ಲೆಕ್ಕಾ ಹೇಳಿದ ಮೌಲ್ಯಗಳಿಂದ {deviation}% ವಿಚಲನವನ್ನು ತೋರಿಸುತ್ತದೆ.',

    disclaimer:
      'ಈ ವರದಿ LoanGuard AI ನಿಂದ ರಚಿಸಲ್ಪಟ್ಟಿದೆ ಮತ್ತು ಮಾಹಿತಿ ಉದ್ದೇಶಗಳಿಗಾಗಿ ಮಾತ್ರ ಉಪಲಬ್ಧವಾಗಿದೆ. ಇದು ಪರವಾನಗಿ ಪ್ರಾಪ್ತ ಕಾನೂನು ಸಲಹೆ, ನಿಯಂತ್ರಕ ನಿರ್ದೇಶನ ಅಥವಾ ವೃತ್ತಿಪರ ಆರ್ಥಿಕ ಸಲಹೆಗೆ ಪರ್ಯಾಯವಲ್ಲ.',
  },

  ml: {
    title: 'LoanGuard അനുസരണ റിപ്പോർട്ട്',
    subtitle: 'വായ്പ കരാർ വിശകലനം',
    generatedOn: 'സൃഷ്ടിച്ച തീയതി',
    bank: 'ബാങ്ക്/NBFC',
    borrower: 'വായ്പക്കാരന്റെ പേര്',
    agreementDate: 'കരാർ തീയതി',
    selectLanguage: 'റിപ്പോർട്ട് ഭാഷ',
    downloadButton: 'PDF റിപ്പോർട്ട് ഡൗൺലോഡ് ചെയ്യുക',
    noData: 'വിശകലന ഡാറ്റ ലഭ്യമല്ല. ആദ്യം ഒരു വായ്പ രേഖ അപ്‌ലോഡ് ചെയ്ത് വിശകലനം ചെയ്യുക.',

    systemConfidence: 'സിസ്റ്റം ആത്മവിശ്വാസം',
    docCompleteness: 'രേഖ പൂർണ്ണത',
    lowConfidenceWarning: 'കുറഞ്ഞ ആത്മവിശ്വാസ മുന്നറിയിപ്പ്',

    complianceAssessment: 'അനുസരണ വിലയിരുത്തൽ സംഗ്രഹം',
    violationsFound: 'കണ്ടെത്തിയ ലംഘനങ്ങൾ',
    critical: 'ഗുരുതരം',
    high: 'ഉയർന്ന',
    overchargeEstimate: 'അമിത ഫീസ് അനുമാനം',
    riskCategory: 'അപകട ശ്രേണി',
    appealSuccessProbability: 'അപ്പീൽ വിജയ സാധ്യത',
    mathProven: 'ഗണിതപരമായി തെളിയിക്കപ്പെട്ട ലംഘനങ്ങൾ',
    kfsPresent: 'പ്രധാന വസ്തുത പ്രസ്താവന',

    loanDetails: 'വായ്പ വിശദാംശങ്ങൾ',
    principal: 'മുതൽ',
    interestRate: 'പലിശ നിരക്ക്',
    effectiveAPR: 'യഥാർത്ഥ APR',
    tenure: 'കാലാവധി',
    expectedEMI: 'പ്രതീക്ഷിക്കുന്ന EMI',
    statedEMI: 'പ്രസ്താവിത EMI',
    processingFee: 'പ്രോസസ്സിംഗ് ഫീസ്',
    overchargeEst: 'അമിത ഫീസ് അനുമാനം',
    months: 'മാസങ്ങൾ',
    prepaymentPenalty: 'മുൻകൂർ അടവ് പിഴ',
    insurancePremium: 'ഇൻഷുറൻസ് പ്രീമിയം',

    flags: 'കണ്ടെത്തിയ ഫ്ലാഗുകൾ',
    autoDebit: 'ഓട്ടോ-ഡെബിറ്റ് മാൻഡേറ്റ്',

    riskIntelligence: 'അപകട ബുദ്ധിമത്ത സ്കോർ',
    score: 'സ്കോർ',
    lowRisk: 'കുറഞ്ഞ അപകടം',
    emiDeviation: 'EMI വ്യതിയാനം',
    hiddenFees: 'മറഞ്ഞിരിക്കുന്ന ഫീസ്',
    rbiViolations: 'RBI ലംഘനങ്ങൾ',
    penalStacking: 'ശിക്ഷാ സ്റ്റാക്കിംഗ്',
    transparency: 'സുതാര്യത',
    ambiguity: 'അവ്യക്തത',
    behavioralRisk: 'പെരുമാറ്റ അപകടം',

    emiAnalysis: 'EMI വിശകലനം',
    emiNote: 'നിർണ്ണായക EMI കണക്കുകൂട്ടൽ പ്രസ്താവിത മൂല്യങ്ങളിൽ നിന്ന് {deviation}% വ്യതിയാനം കാണിക്കുന്നു.',

    disclaimer:
      'ഈ റിപ്പോർട്ട് LoanGuard AI സൃഷ്ടിച്ചതാണ്, ഇത് വിവരദാന ആവശ്യങ്ങൾക്ക് മാത്രമുള്ളതാണ്. ഇത് ലൈസൻസ് ഉള്ള നിയമോപദേശം, നിയന്ത്രണ മാർഗ്ഗനിർദ്ദേശം, അല്ലെങ്കിൽ പ്രൊഫഷണൽ സാമ്പത്തിക ഉപദേശത്തിന് പകരമല്ല.',
  },
};

// ── Type-safe translation getter ──────────────────────────────────────────────
// Falls back to English if a key is missing in the target language.

export const getTranslation = (
  language: Language,
  key: keyof typeof reportTranslations.en
): string => {
  return (
    (reportTranslations[language] as typeof reportTranslations.en)[key] ??
    reportTranslations.en[key]
  );
};

// ── Helper: get all keys for TypeScript validation ────────────────────────────
// Ensures every non-English language has all keys at compile time.

type TranslationShape = typeof reportTranslations.en;

// This type assertion will error at compile time if any language is missing a key.
// eslint-disable-next-line @typescript-eslint/no-unused-vars
const _validateTranslations: Record<Language, TranslationShape> =
  reportTranslations as Record<Language, TranslationShape>;
